/**
 * Draft Mode Enable Route — Stage 4.4
 *
 * Activates Next.js Draft Mode using the secure Sanity preview URL secret mechanism.
 *
 * How it works:
 *   1. Sanity Presentation Tool calls this route with a short-lived preview secret
 *      appended as a URL parameter (generated by @sanity/preview-url-secret).
 *   2. `defineEnableDraftMode` from `next-sanity/draft-mode` validates the secret
 *      against Sanity's Content Lake using the SANITY_API_READ_TOKEN.
 *   3. If valid → Next.js Draft Mode cookie is set → editor is redirected to the
 *      storefront URL specified by the Presentation Tool.
 *   4. If invalid → 401 response. No Draft Mode is activated.
 *
 * Security:
 *   - Preview secrets are short-lived and validated server-side against Sanity.
 *   - SANITY_API_READ_TOKEN stays server-side — never reaches the browser.
 *   - There is no way for a public user to activate Draft Mode without a valid secret.
 *   - Cross-site iframe preview (Presentation Tool in Studio) uses CHIPS-partitioned
 *     cookies automatically (handled internally by defineEnableDraftMode).
 *
 * Usage (automatically called by Presentation Tool):
 *   GET /api/draft-mode/enable?sanityPreviewSecret=<secret>&redirect=/journal/article-slug
 *
 * Reference:
 *   https://www.sanity.io/docs/preview-url-secret
 */

import { defineEnableDraftMode } from "next-sanity/draft-mode";
import { getSanityClient } from "@/lib/cms/providers/sanity/client";
import { isSanityConfigured } from "@/lib/cms/providers/sanity/config";
import { createClient } from "next-sanity";

// The preview client must use the read token so validatePreviewUrl can
// query Sanity for the stored short-lived secret record.
// This is server-side only — SANITY_API_READ_TOKEN must never be NEXT_PUBLIC_.
//
// We use a dummy fallback client if Sanity is not configured (e.g. during CI build)
// to prevent module evaluation from throwing an error and crashing `next build`.
const client = isSanityConfigured()
  ? getSanityClient()
  : createClient({ projectId: "dummy", dataset: "dummy" });

export const { GET } = defineEnableDraftMode({
  client,
});
